name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Use the .NET version you need

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t nghialoe/dockercicd:latest .

    - name: Push Docker image to Docker Hub
      run: docker push nghialoe/dockercicd:latest
