name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if [ $? -ne 0 ]; then
          echo "Docker login failed"
          exit 1
        fi

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dockercicd:latest -f Docker-Ci-Di/Dockerfile .

    - name: List Docker images
      run: docker images

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/dockercicd:latest
        if [ $? -ne 0 ]; then
          echo "Docker push failed"
          exit 1
        fi

    - name: Install jq for JSON processing
      run: sudo apt-get install -y jq

    - name: Push to Railway
      run: |
        IMAGE="${{ secrets.DOCKER_USERNAME }}/dockercicd:latest"
        PAYLOAD=$(jq -n --arg image "$IMAGE" '{"image": $image}')
        
        curl -X POST "https://backboard.railway.app/v1/projects/${{ secrets.RAILWAY_PROJECT_ID }}/services/${{ secrets.RAILWAY_SERVICE_ID }}/deploy" \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data "$PAYLOAD"
        if [ $? -ne 0 ]; then
          echo "Railway deployment failed"
          exit 1
        fi